Gracefully handle launchctl failure, using reattach script if possible. Documented here: http://stackoverflow.com/questions/10193561/tmux-socket-is-not-connected-error-on-os-x-lion

diff --git a/runcoms/zlogin b/runcoms/zlogin
--- a/runcoms/zlogin
+++ b/runcoms/zlogin
@@ -16,7 +16,11 @@
   # Set environment variables for launchd processes.
   if [[ "$OSTYPE" == darwin* ]]; then
     for env_var in PATH MANPATH; do
-      launchctl setenv "$env_var" "${(P)env_var}"
+      if which reattach-to-user-namespace > /dev/null; then
+        reattach-to-user-namespace launchctl setenv "$env_var" "${(P)env_var}"
+      else
+        launchctl setenv "$env_var" "${(P)env_var}" || echo "Launchctl error, possible solution: Install reattach-to-user-namespace"
+      fi
     done
   fi
 } &!
