modules: firefox-profile: minor update (removed NULL_GLOB in favor of (N))

diff --git a/modules/firefox-profile/functions/fhp b/modules/firefox-profile/functions/fhp
--- a/modules/firefox-profile/functions/fhp
+++ b/modules/firefox-profile/functions/fhp
@@ -24,10 +24,13 @@ local ext=.tar.$compressor[(w)1]
 pushd -q "$HOME"/.mozilla/firefox || return
 
 if [[ -f $profile/.unpacked ]] {
-	mv -f $profile{,.old}$ext
-	if (( $? )) {
-		die "failed to override the old tarball"
-		return
+	if [[ -f $profile$ext ]] {
+		mv -f $profile{,.old}$ext
+		if (( $? )) {
+			die "failed to override the old tarball"
+			popd -q
+			return
+		}
 	}
 
 	tar -X $profile/.unpacked -Ocp $profile | $=compressor $profile$ext
